# 🐙 Using node 16.x image, run jest unit tests in GitHub Actions.
# You can create your first workflow yml by https://github.com/[YOUR GIT NAME]/[YOUR REPO NAME]/actions/new
name: Build

on:
  push:
    branches: [dev, main]
  pull_request:
    branches: [dev, main]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [16.x]

    steps:
      - uses: actions/checkout@v3
      - name: Run tests - Node ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
          cache: "npm"
      - run: npm install
      - run: npm run test
        # Publish to npmjs
        if: endsWith(github.ref, 'main')
      - uses: JS-DevTools/npm-publish@v1
        with:
          token: ${{ secrets.NPM_TOKEN }}
